// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WpfApp3.Migrations
{
    [DbContext(typeof(SqlLiteDbContext))]
    [Migration("20230607124157_Add")]
    partial class Add
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageScoreOfCertificate")
                        .HasColumnType("REAL");

                    b.Property<bool>("Certificate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date_of_Birth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabilityCertificate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enrollment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinishedOnly")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FullYears")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GraduatedFromGrades")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Money")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Orphan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfResidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Snils")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfAdmission")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
